In [9]:
### Import all necessary packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.preprocessing import StandardScaler, LabelEncoder

import keras
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

### Data Exploration and Preprocessing

In [2]:
### Load the dataset
df=pd.read_csv('sonardataset.csv')

In [3]:
### Data size
df.shape

(208, 61)

In [5]:
### Data information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x_1     208 non-null    float64
 1   x_2     208 non-null    float64
 2   x_3     208 non-null    float64
 3   x_4     208 non-null    float64
 4   x_5     208 non-null    float64
 5   x_6     208 non-null    float64
 6   x_7     208 non-null    float64
 7   x_8     208 non-null    float64
 8   x_9     208 non-null    float64
 9   x_10    208 non-null    float64
 10  x_11    208 non-null    float64
 11  x_12    208 non-null    float64
 12  x_13    208 non-null    float64
 13  x_14    208 non-null    float64
 14  x_15    208 non-null    float64
 15  x_16    208 non-null    float64
 16  x_17    208 non-null    float64
 17  x_18    208 non-null    float64
 18  x_19    208 non-null    float64
 19  x_20    208 non-null    float64
 20  x_21    208 non-null    float64
 21  x_22    208 non-null    float64
 22  x_23    208 non-null    float64
 23  x_24    208 non-null    float64
 24  x_25    208 non-null    float64
 25  x_26    208 non-null    float64
 26  x_27    208 non-null    float64
 27  x_28    208 non-null    float64
 28  x_29    208 non-null    float64
 29  x_30    208 non-null    float64
 30  x_31    208 non-null    float64
 31  x_32    208 non-null    float64
 32  x_33    208 non-null    float64
 33  x_34    208 non-null    float64
 34  x_35    208 non-null    float64
 35  x_36    208 non-null    float64
 36  x_37    208 non-null    float64
 37  x_38    208 non-null    float64
 38  x_39    208 non-null    float64
 39  x_40    208 non-null    float64
 40  x_41    208 non-null    float64
 41  x_42    208 non-null    float64
 42  x_43    208 non-null    float64
 43  x_44    208 non-null    float64
 44  x_45    208 non-null    float64
 45  x_46    208 non-null    float64
 46  x_47    208 non-null    float64
 47  x_48    208 non-null    float64
 48  x_49    208 non-null    float64
 49  x_50    208 non-null    float64
 50  x_51    208 non-null    float64
 51  x_52    208 non-null    float64
 52  x_53    208 non-null    float64
 53  x_54    208 non-null    float64
 54  x_55    208 non-null    float64
 55  x_56    208 non-null    float64
 56  x_57    208 non-null    float64
 57  x_58    208 non-null    float64
 58  x_59    208 non-null    float64
 59  x_60    208 non-null    float64
 60  Y       208 non-null    object
dtypes: float64(60), object(1)
memory usage: 99.3+ KB

In [6]:
### first five rows of data
df.head()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60,Y
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [7]:
### Statistical Summary
df.describe()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_51,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [8]:
### Check Duplicates
df.duplicated().sum()

np.int64(0)

In [10]:
### Check Missing values
df.isnull().sum().sum()

np.int64(0)

In [12]:
pd.unique(df['Y'])

array(['R', 'M'], dtype=object)

     2 classes: Mine (M) and Rock (R)

### Model Implementation

In [4]:
### Seperate Features  and Target
target=df['Y']
features=df.drop('Y',axis=1)

In [5]:
### Encoding
lab_en=LabelEncoder()
target=lab_en.fit_transform(target)

In [8]:
### Train_Test_Split
x_train, x_test, y_train, y_test = train_test_split(features,target,test_size=0.2,random_state=100,stratify=target)

print("Training Features:", x_train.shape)
print("Testing Features :", x_test.shape)
print("Training Target  :", y_train.shape)
print("Testing Target   :", y_test.shape)

Training Features: (166, 60)
Testing Features : (42, 60)
Training Target  : (166,)
Testing Target   : (42,)

In [10]:
### Scaling
std_sca = StandardScaler()

x_train = std_sca.fit_transform(x_train)
x_test = std_sca.transform(x_test)

* The input features were normalized using StandardScaler.
* The scaler was fitted on the training data and then applied to the test data.
* This helps the ANN converge faster and improves model performance.

In [12]:
### Basic ANN Model Building

model = Sequential()

# Input layer + Hidden layer
model.add(Dense(32, input_dim=60, activation='relu'))

# Second hidden layer
model.add(Dense(16, activation='relu'))

# Output layer
model.add(Dense(1, activation='sigmoid'))

In [13]:
### Model Compilation
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │           1,952 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,497 (9.75 KB)

 Trainable params: 2,497 (9.75 KB)

 Non-trainable params: 0 (0.00 B)

* The ANN model was successfully constructed using TensorFlow/Keras.
* The model contains two hidden layers with 32 and 16 neurons using the ReLU activation function.
* The output layer contains 1 neuron with the Sigmoid activation function for binary classification.
* The model has a total of 2,497 trainable parameters.

In [15]:
### Model Training and validation
history = model.fit(x_train, y_train, epochs=100, batch_size=1000)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.4880 - loss: 0.7559
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.5181 - loss: 0.7380
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.5361 - loss: 0.7210
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 0.5602 - loss: 0.7047
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - accuracy: 0.5663 - loss: 0.6892
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.5964 - loss: 0.6742
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.6205 - loss: 0.6596
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.6205 - loss: 0.6456
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.6506 - loss: 0.6321
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.6747 - loss: 0.6193
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 199ms/step - accuracy: 0.6928 - loss: 0.6069
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.7048 - loss: 0.5952
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.7169 - loss: 0.5841
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.7289 - loss: 0.5732
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.7410 - loss: 0.5626
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 0.7530 - loss: 0.5524
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.7530 - loss: 0.5426
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.7711 - loss: 0.5329
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.7771 - loss: 0.5235
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.7771 - loss: 0.5143
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.7831 - loss: 0.5053
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.7831 - loss: 0.4964
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.7892 - loss: 0.4877
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.8012 - loss: 0.4792
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - accuracy: 0.8133 - loss: 0.4707
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.8133 - loss: 0.4622
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.8133 - loss: 0.4538
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.8253 - loss: 0.4455
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.8313 - loss: 0.4374
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.8313 - loss: 0.4293
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.8434 - loss: 0.4213
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.8494 - loss: 0.4135
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.8554 - loss: 0.4059
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.8675 - loss: 0.3982
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.8675 - loss: 0.3906
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.8735 - loss: 0.3831
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.8735 - loss: 0.3756
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - accuracy: 0.8735 - loss: 0.3682
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.8795 - loss: 0.3609
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.8976 - loss: 0.3536
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.9036 - loss: 0.3465
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - accuracy: 0.9096 - loss: 0.3394
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.9157 - loss: 0.3324
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.9217 - loss: 0.3255
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.9217 - loss: 0.3187
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.9217 - loss: 0.3122
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.9217 - loss: 0.3058
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.9217 - loss: 0.2994
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.9217 - loss: 0.2932
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.9217 - loss: 0.2871
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.9217 - loss: 0.2811
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.9217 - loss: 0.2753
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.9277 - loss: 0.2695
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.9277 - loss: 0.2638
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.9337 - loss: 0.2582
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.9398 - loss: 0.2527
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.9398 - loss: 0.2473
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - accuracy: 0.9518 - loss: 0.2420
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 195ms/step - accuracy: 0.9518 - loss: 0.2368
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.9578 - loss: 0.2317
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.9578 - loss: 0.2268
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.9578 - loss: 0.2219
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.9578 - loss: 0.2171
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.9578 - loss: 0.2125
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.9639 - loss: 0.2079
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.9639 - loss: 0.2033
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.9639 - loss: 0.1988
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.9639 - loss: 0.1944
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.9639 - loss: 0.1900
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.9639 - loss: 0.1856
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.9639 - loss: 0.1814
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.9759 - loss: 0.1772
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.9759 - loss: 0.1731
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.9759 - loss: 0.1691
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.9759 - loss: 0.1652
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.9880 - loss: 0.1614
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.9880 - loss: 0.1576
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.9940 - loss: 0.1539
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.9940 - loss: 0.1503
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.9940 - loss: 0.1468
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.9940 - loss: 0.1434
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.9940 - loss: 0.1400
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.9940 - loss: 0.1368
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.9940 - loss: 0.1336
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - accuracy: 0.9940 - loss: 0.1304
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.9940 - loss: 0.1273
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.9940 - loss: 0.1243
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.9940 - loss: 0.1213
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.9940 - loss: 0.1184
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.9940 - loss: 0.1155
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.9940 - loss: 0.1128
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 0.9940 - loss: 0.1101
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.9940 - loss: 0.1075
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.9940 - loss: 0.1049
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.9940 - loss: 0.1024
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.9940 - loss: 0.1000
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.9940 - loss: 0.0976
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - accuracy: 0.9940 - loss: 0.0953
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.9940 - loss: 0.0931
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.9940 - loss: 0.0909

In [17]:
### Prediction
y_pred_prob = model.predict(x_test)

y_pred = (y_pred_prob > 0.5).astype(int)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

In [24]:
### Evaluation
print("Accuracy :", accuracy_score(y_test, y_pred))
print()
print("classification Report")
print(classification_report(y_test, y_pred))

Accuracy : 0.7619047619047619

classification Report
              precision    recall  f1-score   support

           0       0.77      0.77      0.77        22
           1       0.75      0.75      0.75        20

    accuracy                           0.76        42
   macro avg       0.76      0.76      0.76        42
weighted avg       0.76      0.76      0.76        42

* The model achieved an accuracy of 76.19% on the test data.
* The precision is 75%, indicating that 75% of the samples predicted as mines were correctly classified.
* The recall is 75%, meaning the model correctly identified 75% of the actual positive samples.
* The F1-score is 75%, showing a balanced performance between precision and recall.
* Overall, the basic ANN model provides a reasonable classification performance for distinguishing between mines and rocks.

### Hyperparameter Tuning

In [25]:
!pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in c:\users\rskar\anaconda3\lib\site-packages (from keras-tuner) (3.14.1)
Requirement already satisfied: packaging in c:\users\rskar\anaconda3\lib\site-packages (from keras-tuner) (25.0)
Requirement already satisfied: requests in c:\users\rskar\anaconda3\lib\site-packages (from keras-tuner) (2.32.5)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in c:\users\rskar\anaconda3\lib\site-packages (from keras-tuner) (1.81.1)
Requirement already satisfied: protobuf in c:\users\rskar\anaconda3\lib\site-packages (from keras-tuner) (7.35.1)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\rskar\anaconda3\lib\site-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in c:\users\rskar\anaconda3\lib\site-packages (from keras->keras-tuner) (2.4.0)
Requirement already satisfied: numpy in c:\users\rskar\anaconda3\lib\site-packages (from keras->keras-tuner) (2.3.5)
Requirement already satisfied: rich in c:\users\rskar\anaconda3\lib\site-packages (from keras->keras-tuner) (14.2.0)
Requirement already satisfied: namex in c:\users\rskar\anaconda3\lib\site-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in c:\users\rskar\anaconda3\lib\site-packages (from keras->keras-tuner) (3.14.0)
Requirement already satisfied: optree in c:\users\rskar\anaconda3\lib\site-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in c:\users\rskar\anaconda3\lib\site-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\rskar\anaconda3\lib\site-packages (from requests->keras-tuner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rskar\anaconda3\lib\site-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rskar\anaconda3\lib\site-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rskar\anaconda3\lib\site-packages (from requests->keras-tuner) (2025.11.12)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\rskar\anaconda3\lib\site-packages (from rich->keras->keras-tuner) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\rskar\anaconda3\lib\site-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\rskar\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner

   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   ---------------------------------------- 2/2 [keras-tuner]

Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [26]:
def build_model(hp):

    model = Sequential()

    # First Hidden Layer
    model.add(Dense(
        units=hp.Int('units1', min_value=16, max_value=64, step=16),
        activation=hp.Choice('activation1', ['relu', 'tanh']),
        input_shape=(60,)
    ))

    # Second Hidden Layer
    model.add(Dense(
        units=hp.Int('units2', min_value=8, max_value=32, step=8),
        activation=hp.Choice('activation2', ['relu', 'tanh'])
    ))

    # Output Layer
    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer=Adam(
            learning_rate=hp.Choice(
                'learning_rate',
                values=[0.01, 0.001, 0.0001]
            )
        ),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [28]:
import keras_tuner as kt
tuner = kt.RandomSearch(
    hypermodel=build_model,
    objective='val_accuracy',
    max_trials=10,
    overwrite=True,
    directory='random_search',
    project_name='sonar_ann'
)

In [32]:
tuner.search(
    x_train,
    y_train,
    epochs=50,
    validation_split=0.2,
    verbose=1
)

Trial 10 Complete [00h 00m 19s]
val_accuracy: 0.8823529481887817

Best val_accuracy So Far: 0.8823529481887817
Total elapsed time: 00h 04m 28s

In [34]:
best_model = tuner.get_best_models(num_models=1)[0]

In [35]:
best_hp = tuner.get_best_hyperparameters(num_trials=1)[0]

print("Units in Hidden Layer 1:", best_hp.get('units1'))
print("Activation 1:", best_hp.get('activation1'))
print("Units in Hidden Layer 2:", best_hp.get('units2'))
print("Activation 2:", best_hp.get('activation2'))
print("Learning Rate:", best_hp.get('learning_rate'))

Units in Hidden Layer 1: 64
Activation 1: tanh
Units in Hidden Layer 2: 32
Activation 2: tanh
Learning Rate: 0.01

In [37]:
y_pred_prob = best_model.predict(x_test)
y_pred = (y_pred_prob > 0.5).astype(int)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

### Evaluation

In [38]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print()
print("classification Report")
print(classification_report(y_test, y_pred))

Accuracy : 0.7619047619047619

classification Report
              precision    recall  f1-score   support

           0       0.83      0.68      0.75        22
           1       0.71      0.85      0.77        20

    accuracy                           0.76        42
   macro avg       0.77      0.77      0.76        42
weighted avg       0.77      0.76      0.76        42

* Random Search was used to optimize the ANN hyperparameters.
* The best model used:
* Hidden Layer 1: 64 neurons
* Activation Function 1: tanh
* Hidden Layer 2: 32 neurons
* Activation Function 2: tanh
* Learning Rate: 0.01
* The highest validation accuracy obtained during tuning was 88.24%.
* When evaluated on the test dataset, the tuned model achieved an accuracy of 76.19%.

**Comparison**

| Metric | Basic ANN | Tuned ANN |
|---------|----------:|----------:|
| Accuracy | 76.19% | 76.19% |
| Precision | 75.00% | 77.00% |
| Recall | 75.00% | 77.00% |
| F1-Score | 75.00% | 76.00% |

**Conclusion**
* Random Search successfully identified a better set of hyperparameters.
* The tuned model achieved a higher validation accuracy (88.24%) during tuning.
* However, the test accuracy remained the same (76.19%) as the basic ANN model.
* This indicates that hyperparameter tuning improved performance on the validation data but did not improve generalization on the test dataset.
* Overall, both the basic ANN and the tuned ANN performed similarly on the unseen test data.

    A basic ANN model was developed to classify sonar signals as mines or rocks. The model was trained and evaluated using accuracy, precision, recall, and F1-score. Hyperparameter tuning was performed using Random Search by varying the number of neurons, activation functions, and learning rate. The tuned model identified a better hyperparameter combination, but its test accuracy remained 76.19%, which was similar to the basic ANN model. This indicates that, for this dataset, hyperparameter tuning did not improve the model's performance on unseen test data.